controllers/home.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from model import helpers, dbmain, dbproj

home = Blueprint('home', __name__,
                        template_folder='../templates/home')

@home.route('/')
def homepage():
    if 'id' in session:
        # user is logged in, go to the portal
        return redirect(url_for('portal.portal_page'))
    else:
        return render_template('homepage.html')

@home.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    elif request.method == 'POST':
        authenticated = dbmain.authenticate(request.form['username'], request.form['password'])
        if authenticated:
            user_id = str(dbmain.userByUsername(request.form['username'])['_id'])
            session['id'] = user_id
            return redirect(url_for('home.homepage'))
        else:
            return render_template('login.html', error='Your login credentials were incorrect.')

@home.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    if request.method == 'POST':
        # submitted register form, so register the user
        req_fields = ['first', 'last', 'email', 'username', 'password', 'password_confirm', 'acct_type', 'school', 'timezone']
        for field in req_fields:
            if request.form[field] == '':
                return render_template('register.html', error='All fields must be complete in order to register.')
        if request.form['password'] != request.form['password_confirm']:
            return render_template('register.html', error='Your passwords did not match.')
        if (request.form['acct_type'] == "None"):
            return render_template('register.html', error='You must select an account type.')
        if (request.form['timezone'] == "None"):
            return render_template('register.html', error='You must select a time zone.')
        # need to add username checking to see if username already exists
        if (not dbmain.usernameAvailable(request.form['username'])):
            return render_template('register.html', error='Your requested username is already taken.')
        user_id = dbmain.addUser(request.form['username'], helpers.get_hashed_password(request.form['password']), request.form['first'], request.form['last'], request.form['email'], request.form['acct_type'], request.form['school'], request.form['timezone'])
        # if the user is a student, create their project
        if request.form['acct_type'] == "Student":
            dbproj.createProjectForUser(user_id)
        session['id'] = str(user_id)
        return redirect(url_for('home.homepage'))

@home.route('/about/')
def about():
    return render_template('about.html')

@home.route('/contact/')
def contact():
    return render_template('contact.html')

@home.route('/getstarted/')
def getstarted():
    return render_template('getstarted.html')

templates/home/about.html
{% extends "home/homebase.html" %}

{% block content %}
<h2>About Us</h2>
<hr>
<div class="row">
    <div class="col-md-10">
        <h3>About The Program</h3>
        <p>
            Science Alliance is a student-run mentorship program that aims to help foster a passion for science among younger students at an early age. High school students mentors are paired with motivated younger student buddies (typically 5th graders, but may also be middle school students). Mentors guide these intellectually curious buddies through a science fair project of their choosing.
            <br /><br />
            Along the way, these buddies are introduced to investigative science, develop basic skills in planning, executing, and reporting their activities, and get better prepared for middle school lab science. The culminating event of the year is a science fair, organized and run by the high school students, where the buddies can display their projects and show off their knowledge. For mentors, this provides them an opportunity to get involved with a meaningful community service, to act as a positive role model for younger students, and to strengthen their leadership and personal skills.
            <br /><br />
            Science Alliance Network is designed to help schools create Science Alliance programs, and generate interest in science among youth.
        </p>
    </div>
    <div class="col-md-2"></div>
</div>

<div class="row">
    <h3 style="padding-bottom:70px;">Meet the Team</h3>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="card card-user">
            <div class="content">
                <div class="author">
                    <img class="avatar border-gray" src="{{ url_for( 'static', filename='img/team/christina.jpg' ) }}" alt="..."/>

                      <h4 class="title">Christina Ren<br />
                         <small>Executive Board</small>
                      </h4>
                </div>
                <p class="description text-center">Stanford University Class of 2018</p>
            </div>
            <hr>
            <div class="text-center">
                <a href="mailto:christinaren@gmail.com" class="btn btn-simple"><i class="fa fa-envelope-o"></i></a>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card card-user">
            <div class="content">
                <div class="author">
                    <img class="avatar border-gray" src="{{ url_for( 'static', filename='img/team/brian.jpg' ) }}" alt="..."/>

                      <h4 class="title">Brian Yu<br />
                         <small>Executive Board</small>
                      </h4>
                </div>
                <p class="description text-center">Harvard College Class of 2019</p>
            </div>
            <hr>
            <div class="text-center">
                <a href="mailto:brianyu28@gmail.com" class="btn btn-simple"><i class="fa fa-envelope-o"></i></a>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card card-user">
            <div class="content">
                <div class="author">
                    <img class="avatar border-gray" src="{{ url_for( 'static', filename='img/team/sarah.jpg' ) }}" alt="..."/>

                      <h4 class="title">Sarah Joo<br />
                         <small>Executive Board</small>
                      </h4>
                </div>
                <p class="description text-center">Yale College Class of 2020</p>
            </div>
            <hr>
            <div class="text-center">
                <a href="mailto:sarah.joo@gmail.com" class="btn btn-simple"><i class="fa fa-envelope-o"></i></a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="card">
            <div class="content">
                <div class="author" style="text-align:center;">
                      <h4 class="title">Founders<br /></h4>
                </div>
                <p class="description text-center">
                    <b>Christina Ren</b><br /> Stanford University Class of 2018 <br /><br />
                    <b>Patti Carothers</b><br /> Director, Alameda County Science and Engineering Fair
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card">
            <div class="content">
                <div class="author" style="text-align:center;">
                      <h4 class="title">Advisors<br /></h4>
                </div>
                <p class="description text-center">
                    <b>Patti Carothers</b><br /> Director, Alameda County Science and Engineering Fair <br /><br />
                    <b>Linda Bandrowski</b><br /> Advisor, Monte Vista High School Science Alliance <br /><br />
                    <b>Courtney Corda</b><br /> Advisor, Science Buddies <br /><br />
                    <b>Robin Groch</b><br /> Advisor, San Ramon Valley High School Science Alliance<br /><br />
                </p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card">
            <div class="content">
                <div class="author" style="text-align:center;">
                      <h4 class="title">Web Design<br /></h4>
                </div>
                <p class="description text-center">
                    <b>Brian Yu</b><br /> Harvard College Class of 2019 <br /><br />
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-about').addClass('active');   
});
</script>
{% endblock %}

templates/home/contact.html
{% extends "home/homebase.html" %}


{% block content %}
<h2>Contact Us</h2>
<hr>


<div class="row">
    <div class="col-md-10">
        <h3>Reach the Team</h3>
        <p>
            If you have questions, issues, or are interested in starting a Science Alliance branch of your own, please reach out to Brian Yu at <a href="mailto:brianyu28@gmail.com">brianyu28@gmail.com</a>.
        </p>
    </div>
    <div class="col-md-2"></div>
</div>

{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-contact').addClass('active');   
});
</script>
{% endblock %}

templates/home/getstarted.html
{% extends "home/homebase.html" %}


{% block content %}
<h2>Getting Started</h2>
<hr>
<div class="row">
    <div class="col-md-10">
        <h3>For Students:</h3>
        <p>
            If you have yet to sign up for Science Alliance Network, start by <a href={{ url_for('home.register') }}>registering for an account</a>.
        </p>
    </div>
    <div class="col-md-2"></div>
</div>

{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-getstarted').addClass('active');   
});
</script>
{% endblock %}

templates/home/homebase.html
{% extends "base.html" %}

{% block sidebar %}
<li id="sidebar-home">
    <a href="{{ url_for('home.homepage') }}">
        <p><i class="fa fa-home fa-fw"></i>&nbsp;&nbsp;Home</p>
    </a>
</li>
<li id="sidebar-login">
    <a href="{{ url_for('home.login') }}">
        <p><i class="fa fa-sign-in fa-fw"></i>&nbsp;&nbsp;Log In</p>
    </a>
</li>
<li id="sidebar-register">
    <a href="{{ url_for('home.register') }}">
        <p><i class="fa fa-user fa-fw"></i>&nbsp;&nbsp;Register</p>
    </a>
</li>
<li id="sidebar-about">
    <a href="{{ url_for('home.about') }}">
        <p><i class="fa fa-info-circle fa-fw"></i>&nbsp;&nbsp;About Us</p>
    </a>
</li>
<li id="sidebar-getstarted">
    <a href="{{ url_for('home.getstarted') }}">
        <p><i class="fa fa-flask fa-fw"></i>&nbsp;&nbsp;Get Started</p>
    </a>
</li>
<li id="sidebar-contact">
    <a href="{{ url_for('home.contact') }}">
        <p><i class="fa fa-envelope-o fa-fw"></i>&nbsp;&nbsp;Contact Us</p>
    </a>
</li>
{% endblock %}

templates/home/homepage.html
{% extends "home/homebase.html" %}

{% block content %}
<h2>Science Alliance Network</h2>
<hr>
<div class="row">
    <div class="col-lg-4 col-md-3 col-sm-2"></div>
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card" style="text-align:center;">
            <div class="header">
                <h4 class="title">Log In</h4></div>
            <div class="content">
                <form method="post" action={{ url_for( 'home.login') }}>
                    <input autocomplete="off" style="margin-bottom:10px;" class="form-control home-form" type="text" name="username" placeholder="Username" autofocus>
                    <input autocomplete="off" class="form-control home-form" type="password" name="password" placeholder="Password">
                    <br />
                    <button type="submit" class="btn btn-default"><span class="network-name">Log In</span></button>
                </form>
                <hr>
                <a class="register-link" href={{ url_for( 'home.register') }}>Need an account? Register here.</a>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-3 col-sm-2"></div>
</div>

<div class="row">
    <hr>
    <div class="col-md-7 col-sm-6">
        <h3>Welcome to Science Alliance.</h3>
        <p><b>Science Alliance</b> is a program designed to provide mentorship to young students interested in science research.
            <br />
            <br /> The Science Alliance Network website provides a variety of online resources that make it easy for school districts to organize their own science fairs, and facilitate the process of mentoring young students in their pursuit of scientific research. Science Alliance Network aims to give high schools the resources they need to start their own Science Alliance programs, and provide easy-to-access web services that enhance the science fair process. </p>
    </div>
    <div class="col-md-5 col-sm-6"> <img class="img-responsive" src={{ url_for( 'static', filename='img/mainpage_1.jpg' ) }} alt=""></div>
</div>

<div class="row">
   <hr>
    <div class="col-md-5 col-sm-6"> <img class="img-responsive" src={{ url_for( 'static', filename='img/mainpage_2.jpg' ) }} alt=""></div>
    <div class="col-md-7 col-sm-6">
        <h3>Our Mission</h3>
        <p> The mission of Science Alliance Network is to develop innovative programs to help young students get involved in first-hand scientific research, exploration and investigation. We believe these programs inspire a passion for science and nurture inquisitive habits and reasoning skills. To achieve this goal, Science Alliance Network is focused on fostering Science Alliance branches nationwide. SAN offers many resources to make it easy for high school students and teachers to jump-start their own Science Alliance programs in their local area. </p>
    </div>
</div>
{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-home').addClass('active');   
});
</script>
{% endblock %}

templates/home/login.html
{% extends "home/homebase.html" %}

{% block content %}
<h2>Log In</h2>
<hr>

{% if error is defined %}
<div class="alert alert-danger"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> <strong>Error:</strong> {{ error }} </div>
{% endif %}

<div class="row" style="text-align:center;">
    <div class="col-lg-4 col-md-3 col-sm-2"></div>
    <div class="col-lg-4 col-md-6 col-sm-8">
        <h3>Log In to Science Alliance</h3>
        <form method="post" action={{ url_for( 'home.login') }}>
            <input autocomplete="off" style="margin-bottom:10px;" type="text" class="form-control" name="username" placeholder="Username" autofocus>
            <input autocomplete="off" type="password" class="form-control" name="password" placeholder="Password">
            <br />
            <button type="submit" class="btn btn-default">Log In</button>
        </form>
        <hr> <a class="register-link" href={{ url_for( 'home.register') }}>Need an account? Register here.</a> </div>
    <div class="col-lg-4 col-md-5 col-sm-2"></div>
</div>
{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-login').addClass('active');   
});
</script>
{% endblock %}

templates/home/register.html
{% extends "home/homebase.html" %}


{% block content %}
<h2>Register</h2>
<hr>
           
{% if error is defined %}
<div class="alert alert-danger">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>Error:</strong> {{ error }}
</div>
{% endif %}

<div class="row" style="text-align:center;">
    <div class="col-lg-4 col-md-3 col-sm-2"></div>
    <div class="col-lg-4 col-md-6 col-sm-8">
        <h3>Join Science Alliance Network</h3>
        <hr>
            <form method="post" action={{ url_for('home.register') }}>
                <h5>Basic Information</h5>
                <input autocomplete="off" style="margin-bottom:10px;" type="text" class="form-control" name="first" placeholder="First Name" autofocus>
                <input autocomplete="off" style="margin-bottom:10px;" type="text" class="form-control" name="last" placeholder="Last Name">
                <input autocomplete="off" type="email" class="form-control" name="email" placeholder="Email Address">
                <br />
                <h5>Account Information</h5>
                <input autocomplete="off" style="margin-bottom:10px;" type="text" class="form-control" name="username" placeholder="Desired Username">
                <input autocomplete="off" style="margin-bottom:10px;" type="password" class="form-control" name="password" placeholder="Password">
                <input autocomplete="off" style="margin-bottom:10px;" type="password" class="form-control" name="password_confirm" placeholder="Confirm Password">
                <select style="margin-bottom:10px;" class="form-control" name="acct_type">
                   <option value="None">Select Account Type</option>
                    <option value="Student">Student</option>
                    <option value="Mentor">Mentor</option>
                    <option value="Administrator">Administrator</option>
                </select>
                <input autocomplete="off" style="margin-bottom:10px;" type="text" class="form-control" name="school" placeholder="School">
                <select style="margin-bottom:10px;" class="form-control" name="timezone">
                   <option value="None">Select Time Zone</option>
                   <option value="America/New_York">Eastern Time</option>
                   <option value="America/Chicago">Central Time</option>
                   <option value="America/Denver">Mountain Time</option>
                   <option value="America/Phoenix">Mountain Time (no DST)</option>
                   <option value="America/Los_Angeles">Pacific Time</option>
                   <option value="America/Alaska">Alaskan Time</option>
                   <option value="America/Hawaii">Hawaiian Time</option>
                </select>
                <button type="submit" class="btn btn-default">Register</button>
            </form>

    </div>
    <div class="col-lg-4 col-md-3 col-sm-2"></div>
</div>

{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-register').addClass('active');   
});
</script>
{% endblock %}