controllers/ajax.py
from flask import jsonify, Blueprint, render_template, request, session, redirect, url_for
from model import helpers, dbmain, dbproj, dbcomm, dbtasks
from time import time
from bson import ObjectId
import json
import mailer
import threading

ajax = Blueprint('ajax', __name__,
                        template_folder='../templates/ajax')

@ajax.route('/fair_details/', methods=['POST'])
def fair_details():
    fair = dbmain.fair(request.form['id'])
    return jsonify(name=fair['name'], location=fair['location'], date=fair['date'], id=str(fair['_id']), private=fair['private'])

@ajax.route('/fair_update/', methods=['POST'])
def fair_update():
    dbmain.updateFair(ObjectId(request.form['id']), request.form['name'], request.form['date'], request.form['location'], request.form['private'])
    return jsonify(result="Success")

@ajax.route('/make_primary/', methods=['POST'])
def make_primary():
    dbmain.changePrimaryFair(ObjectId(session['id']), ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/approve_user/', methods=['POST'])
def approve_user():
    dbmain.approveUser(ObjectId(request.form['user']), ObjectId(request.form['fair']))
    return jsonify(result="Success")

@ajax.route('/reject_user/', methods=['POST'])
def reject_user():
    dbmain.removeRegistration(ObjectId(request.form['user']), ObjectId(request.form['fair']))
    return jsonify(result="Success")

@ajax.route('/students_to_pair/', methods=['POST'])
def students_to_pair():
    students = dbmain.studentsToPair(ObjectId(request.form['fair']), request.form['repeats'])
    result = []
    for student in students:
        result.append({"id":str(student['_id']), "first":student['first'], "last":student['last']})
    return jsonify(result)

@ajax.route('/mentors_to_pair/', methods=['POST'])
def mentors_to_pair():
    mentors = dbmain.mentorsToPair(ObjectId(request.form['fair']), request.form['repeats'])
    result = []
    for mentor in mentors:
        result.append({"id":str(mentor['_id']), "first":mentor['first'], "last":mentor['last']})
    return jsonify(result)

@ajax.route('/pair/', methods=['POST'])
def pair():
    if not dbmain.pairingExists(ObjectId(request.form['fair']), ObjectId(request.form['student']), ObjectId(request.form['mentor'])):
        dbmain.addPairing(ObjectId(request.form['fair']), ObjectId(request.form['student']), ObjectId(request.form['mentor']))
        if not dbmain.hasPrimaryPartner(ObjectId(request.form['student'])):
            dbmain.changePrimaryPartner(ObjectId(request.form['student']), ObjectId(request.form['mentor']))
        if not dbmain.hasPrimaryPartner(ObjectId(request.form['mentor'])):
            dbmain.changePrimaryPartner(ObjectId(request.form['mentor']), ObjectId(request.form['student']))
        # create a conversation between the two partners if it does not exist yet
        dbcomm.addConversation([ObjectId(request.form['student']), ObjectId(request.form['mentor'])])
    return jsonify(result="Success")

@ajax.route('/remove_pairing/', methods=['POST'])
def remove_pairing():
    dbmain.deletePairingByID(ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/mentors_needing_trainers/', methods=['POST'])
def mentors_needing_trainers():
    mentors = dbmain.mentorsNeedingTrainers(ObjectId(request.form['fair']), request.form['repeats'])
    result = []
    for mentor in mentors:
        result.append({"id":str(mentor['_id']), "first":mentor['first'], "last":mentor['last']})
    return jsonify(result)

@ajax.route('/fair_administrators/', methods=['POST'])
def fair_administrators():
    administrators = dbmain.administrators(ObjectId(request.form['fair']))
    result = []
    for admin in administrators:
        result.append({"id":str(admin["_id"]), "first":admin["first"], "last":admin["last"]})
    return jsonify(result)

@ajax.route('/pair_trainer/', methods=['POST'])
def pair_trainer():
    if not dbmain.trainingExists(ObjectId(request.form['fair']), ObjectId(request.form['mentor']), ObjectId(request.form['trainer'])):
        dbmain.assignTrainer(ObjectId(request.form['fair']), ObjectId(request.form['mentor']), ObjectId(request.form['trainer']))
    dbcomm.addConversation([ObjectId(request.form['mentor']), ObjectId(request.form['trainer'])])
    return jsonify(result="Success")

@ajax.route('/remove_training/', methods=['POST'])
def remove_training():
    dbmain.deleteTrainingByID(ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/post_announcement/', methods=['POST'])
def post_announcement():
    dbmain.addAnnouncement(ObjectId(request.form['fair']), ObjectId(request.form['author']), time(), request.form['title'], request.form['contents'])
    return jsonify(result="Success")

@ajax.route('/remove_announcement/', methods=['POST'])
def remove_announcement():
    dbmain.deleteAnnouncementByID(ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/update_permissions/', methods=['POST'])
def update_permissions():
    dbmain.setAccessLevel(ObjectId(request.form['user']), ObjectId(request.form['fair']), request.form['level'])
    return jsonify(result="Success")

@ajax.route('/make_primary_partner/', methods=['POST'])
def make_primary_partner():
    dbmain.changePrimaryPartner(ObjectId(session['id']), ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/update_project/', methods=['POST'])
def update_project():
    dbproj.editProject(ObjectId(request.form['project_id']), request.form['field'], request.form['value'])
    return jsonify(result="Success")

@ajax.route('/project_field/', methods=['POST'])
def project_field():
    result = dbproj.projectField(ObjectId(request.form['project_id']), request.form['field'])
    return jsonify(result=result)

@ajax.route('/messages_in_conversation/', methods=['POST'])
def messages_in_conversation():
    conversation_id = request.form['conversation_id']
    messages = dbcomm.messagesInConversation(ObjectId(conversation_id))
    members = dbcomm.convoMembers(ObjectId(session['id']), dbcomm.conversationByID(ObjectId(conversation_id)), True)
    return jsonify(messages=messages, members=members)

@ajax.route('/send_message/', methods=['POST'])
def send_message():
    conversation_id = request.form['conversation_id']
    author_id = session['id']
    timestamp = time()
    subject = request.form['subject']
    message = request.form['message']
    dbcomm.addMessage(ObjectId(conversation_id), ObjectId(author_id), timestamp, subject, message)
    # get recipients of message
    members = dbcomm.otherUsersInConversation(ObjectId(author_id), dbcomm.conversationByID(ObjectId(conversation_id)))
    # send message
    t = threading.Thread(target=mailer.send_new_message_mail, args=[members, dbmain.currentUser(), message])
    t.setDaemon(False)
    t.start()
    return jsonify(result="Success")

@ajax.route('/get_conversations/', methods=['POST'])
def get_conversations():
    user_id = ObjectId(session['id'])
    conversations = dbcomm.conversationsForUser(user_id)
    return jsonify(conversations=conversations)

@ajax.route('/get_watched_conversations/', methods=['POST'])
def get_watched_conversations():
    user_id = ObjectId(session['id'])
    conversations = dbcomm.watchedConversationsForUser(user_id)
    return jsonify(conversations=conversations)

@ajax.route('/new_conversation/', methods=['POST'])
def new_conversation():
    members = []
    requested_members = json.loads(request.form['members'])
    if len(requested_members) == 0:
        return jsonify(result=0)
    for member in requested_members:
        members.append(ObjectId(member))
    members.append(ObjectId(session['id']))
    if dbcomm.conversationExists(members):
        return jsonify(result=-1)
    else:
        inserted_id = str(dbcomm.addConversation(members))
        return jsonify(result=1, convo_id=inserted_id)
    
@ajax.route('/submit_for_approval/', methods=['POST'])
def submit_for_approval():
    author_id = ObjectId(request.form['author_id'])
    fair_id = ObjectId(request.form['fair_id'])
    dbproj.changeApprovalStatus(author_id, fair_id, -1)
    return jsonify(result="Success")

@ajax.route('/change_approval_status/', methods=['POST'])
def change_approval_status():
    author_id = ObjectId(request.form['author_id'])
    fair_id = ObjectId(request.form['fair_id'])
    new_status = request.form['new_status']
    dbproj.changeApprovalStatus(author_id, fair_id, new_status)
    return jsonify(result="Success")

@ajax.route('/add_task/', methods=['POST'])
def add_task():
    name = request.form['name']
    value = request.form['value']
    fair_id = ObjectId(request.form['fair_id'])
    task_id = dbtasks.createTask(fair_id, name, value)
    dbtasks.generateProgressesForTask(task_id)
    return jsonify(result="Success")

@ajax.route('/get_tasks/', methods=['POST'])
def get_tasks():
    fair_id = ObjectId(request.form['fair_id'])
    tasks = dbtasks.tasksForFair(fair_id)
    return jsonify(tasks=tasks)

@ajax.route('/edit_task/', methods=['POST'])
def edit_task():
    name = request.form['name']
    value = request.form['value']
    task_id = ObjectId(request.form['task_id'])
    dbtasks.editTask(task_id, name, value)
    return jsonify(result="Success")

@ajax.route('/delete_task/', methods=['POST'])
def delete_task():
    task_id = ObjectId(request.form['task_id'])
    dbtasks.removeTask(task_id)
    return jsonify(result="Success")

@ajax.route('/update_progress/', methods=['POST'])
def update_progress():
    user_id = ObjectId(request.form['user_id'])
    task_id = ObjectId(request.form['task_id'])
    points = request.form['points']
    none = request.form['none'] == "true"
    dbtasks.updateProgress(user_id, task_id, None if none else points)
    return jsonify(result="Success")

@ajax.route('/change_password/', methods=['POST'])
def change_password():
    user = dbmain.currentUser()
    old_pass = request.form['old_pass']

controllers/messenger.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from model import helpers, dbmain, dbproj, dbcomm
from bson import ObjectId
import re

messenger = Blueprint('messenger', __name__,
                        template_folder='../templates/messenger')

@messenger.before_request
def check():
    if 'id' not in session:
        return redirect(url_for('home.homepage'))
    pfid = dbmain.currentPFID()
    if pfid == None:
        return render_template('errors/no_primary_fair.html', user=dbmain.currentUser())

@messenger.route('/', defaults={'convo_id':None})
@messenger.route('/<convo_id>/')
def message_page(convo_id):
    user = dbmain.currentUser()
    if convo_id != None:
        if not dbcomm.conversationWithIDExists(ObjectId(convo_id)):
            convo_id = None
        elif not dbcomm.userIsInConversation(ObjectId(session['id']), ObjectId(convo_id)) and not dbcomm.userWatchesConversation(ObjectId(session['id']), ObjectId(convo_id)):
            convo_id = None
    conversers = dbcomm.availableConversers(ObjectId(session['id']))
    return render_template('messenger/messages.html', conversers=conversers, user=user, selected=convo_id)

templates/messenger/messages.html
{% extends "messenger/messengerbase.html" %}

{% block head %}
<style>
    .current-convo {
        background-color: #ffff66;
    }

    .convo-bar:hover {
        background-color: #ffffe6;
    }

    .current-convo {
      background-color: #ffff66 !important;
    }
    
    textarea {
        resize: vertical;
    }
</style>
{% endblock %}

{% block contents %}
<div class="row">
   <div class="col-lg-3 col-md-4 col-sm-4">
        <table class="table table-hover">
            <thead>
                <th>Conversations <button data-toggle="modal" data-target="#add-convo-modal" class="btn btn-xs btn-primary" style="float:right;">New</button></th>
            </thead>
            <tbody style="font-size:14px;" id="convo-table-body">
                <tr><td>Loading...</td></tr>
            </tbody>
        </table>
        
        <br /><br />
        <span id="watching-convos-span"></span>
   </div>

   <div id="conversation-div" class="col-lg-9 col-md-8 col-sm-8">
     <div class="card">
         <div style="padding-bottom:10px;" class="header">
             <h4 class="title">Conversation<span id="refresh-span"></span></h4>
             <span id="members-span"></span>
         </div>
     </div>

     <div style="padding-bottom:10px;" class="card">
         <div class="header">
             <h4 class="title">Compose Message</h4>
           </div>
             <div class="contents" style="padding-left:10px;padding-right:10px;">
              <input id="compose-subject" class="form-control" placeholder="Subject" /><br />
              <textarea id="compose-message" class="form-control" rows="5" placeholder="Message"></textarea>
              <br  />
              <span id="send-button-span"></span> <span id="send-result-span"></span>
          </div>
     </div>

     <div style="padding-bottom:10px;" class="card">
          <div class="contents" style="padding-top:10px;padding-left:10px;padding-right:10px;">
              <span id="message-span" style="white-space:pre-line;"></span>
          </div>
     </div>


     </div>
</div>

{% endblock %}

{% block outerbody %}
<div id="add-convo-modal" class="modal fade" role="dialog" tabindex="-1">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add New Conversation</h4>
      </div>
      <div class="modal-body">
        <table style="font-size:14px;" class="table table-hover" id="add-convo-table">
            <thead>
                <th>Check</th>
                <th>Name</th>
                <th>Position</th>
            </thead>
            <tbody>
                {% for converser in conversers %}
                <tr>
                    <td><input class="converser-check" type="checkbox" name="{{ converser['_id']|string }}"></td>
                    <td>{{ converser.first }} {{ converser.last }}</td>
                    <td>{{ converser.acct_type }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <span id="add-result-span"></span>
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
        <button onclick="newConversation()" type="button" class="btn btn-primary btn-sm">New Conversation</button>
      </div>
    </div>

  </div>
</div>
{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-messages").addClass('active');
    $('#conversation-div').hide();
    $('#add-convo-table').DataTable();
    getConversations('');
    
    {% if user["acct_type"] == "Administrator" %}
    getWatchedConversations('');
    {% endif %}
    
    {% if selected != None %}
    showConversation("{{ selected }}");
    {% endif %}
});
     
{% if user["acct_type"] == "Administrator" %}
function getWatchedConversations(convo_id) {
    $.post("{{ url_for('ajax.get_watched_conversations') }}", {}, function(data, textStatus) {
        conversations = data["conversations"];
        convo_table = '<table class="table table-hover">';
        convo_table += '<thead><th>Watching</th></thead>';
        convo_table += '<tbody style="font-size:14px;" id="convo-watching-table">';
        for (var i = 0; i < conversations.length; i++) {
            convo_table += '<tr><td class="convo-bar" id="conversation-' + conversations[i]["_id"] + '" onclick=showConversation("' + conversations[i]["_id"] + '")>';
            convo_table += conversations[i]["name"] + "<br />";
            convo_table += '<small>' + conversations[i]["timestamp"] + '</small>';
            convo_table += '</td></tr>';
        }
        convo_table += '</tbody></table>';
        if (conversations.length > 0)
            $('#watching-convos-span').html(convo_table);
        
         if (convo_id != '') {
            $('#conversation-' + convo_id).addClass("current-convo");
         }
    });
}
{% endif %}
     
function getConversations(convo_id) {
    $.post("{{ url_for('ajax.get_conversations') }}", {}, function(data, textStatus) {
        conversations = data["conversations"];
        convo_table = "";
        for (var i = 0; i < conversations.length; i++) {
            convo_table += '<tr><td class="convo-bar" id="conversation-' + conversations[i]["_id"] + '" onclick=showConversation("' + conversations[i]["_id"] + '")>';
            convo_table += conversations[i]["name"] + "<br />";
            convo_table += '<small>' + conversations[i]["timestamp"] + '</small>';
            convo_table += '</td></tr>';
        }
        $('#convo-table-body').html(convo_table);
        
        if (convo_id != '') {
            $('#conversation-' + convo_id).addClass("current-convo");
        }
    });
}

function showConversation(convo_id) {
   history.pushState({}, document.title, '/messenger/' + convo_id + '/');
   $("td").removeClass("current-convo");
   $("#conversation-" + convo_id).addClass("current-convo");
    var parameters = {
      conversation_id: convo_id
    }

    $.post("{{ url_for('ajax.messages_in_conversation') }}", parameters, function(data, textStatus) {
      members = data["members"];
      messages = data["messages"];

     members_html = "";
      for (var i = 0; i < members.length; i++) {
        members_html += members[i] + '<br  />';
      }
      $('#members-span').html(members_html);
      $('#send-button-span').html('<button onclick=sendMessage("' + convo_id + '") class="btn btn-sm btn-primary">Send</button>');
      $('#refresh-span').html('<button onclick=showConversation("' + convo_id + '") style="float:right;" class="btn btn-primary btn-xs">Refresh</button>');
      $('#conversation-div').show();
      $('#compose-subject').focus();

      messages_html = "";
      for (var i = 0; i < messages.length; i++) {
        // include the message here
          messages_html += messageHTML(messages[i]["author"], messages[i]["subject"], messages[i]["timestamp"], messages[i]["body"]);
      }

      $('#message-span').html(messages_html);
        
        getConversations(convo_id);

    }, "json");
}

function sendMessage(convo_id) {
  var parameters = {
    conversation_id: convo_id,
    subject: $('#compose-subject').val(),
    message: $('#compose-message').val()
  }
  $('#send-result-span').html('Sending...');
  $.post("{{ url_for('ajax.send_message') }}", parameters, function(data, textStatus) {
        $('#message-span').html(messageHTML("{{ user.first }} {{ user.last }}", $('#compose-subject').val(), "Just Now", $('#compose-message').val()) + $('#message-span').html());
      $('#send-result-span').html('Message sent successfully.');
      getConversations(convo_id);
  }, "json");
}
    
function messageHTML(author, subject, timestamp, body) {
    html = "<b>" + author + ": " + subject + "</b><br />";
    html += "<small>" + timestamp + "</small><br />";
    html += body + "<br /><hr>";
    return html
}
     
function newConversation() {
    var selected = [];
    
    $('.converser-check').each(function() {
        if ($(this).prop('checked'))
            selected.push($(this).attr('name')); 
    });
    
    var parameters = {
        members: JSON.stringify(selected)
    }
    
    $.post("{{ url_for('ajax.new_conversation') }}", parameters, function(data, textStatus) {
        result = data["result"];
        if (result == -1)
            $('#add-result-span').html('Conversation already exists.');
        else if (result == 0)
            $('#add-result-span').html('Choose at least one person.');
        else {
            convo_id = data["convo_id"];
            getConversations(convo_id);
            showConversation(convo_id);
            $('#add-convo-modal').modal('toggle');
            $('.converser-check').prop('checked', false);
        }
        
    }, "json");
}


</script>
{% endblock %}

templates/messenger/messengerbase.html
{% extends "portal/portalbase.html" %}

{% block content %}
<h2>Messenger</h2>
<hr>
<div class="row">
    <ul class="nav nav-tabs">
      <li id="navbar-messages"><a href="{{ url_for('messenger.message_page') }}">Messages</a></li>
    </ul>
</div>
<br />
{% block contents %}{% endblock %}
{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-messenger').addClass('active');   
});
</script>
{% endblock %}