controllers/ajax.py
from flask import jsonify, Blueprint, render_template, request, session, redirect, url_for
from model import helpers, dbmain, dbproj, dbcomm, dbtasks
from time import time
from bson import ObjectId
import json
import mailer
import threading

ajax = Blueprint('ajax', __name__,
                        template_folder='../templates/ajax')

@ajax.route('/fair_details/', methods=['POST'])
def fair_details():
    fair = dbmain.fair(request.form['id'])
    return jsonify(name=fair['name'], location=fair['location'], date=fair['date'], id=str(fair['_id']), private=fair['private'])

@ajax.route('/fair_update/', methods=['POST'])
def fair_update():
    dbmain.updateFair(ObjectId(request.form['id']), request.form['name'], request.form['date'], request.form['location'], request.form['private'])
    return jsonify(result="Success")

@ajax.route('/make_primary/', methods=['POST'])
def make_primary():
    dbmain.changePrimaryFair(ObjectId(session['id']), ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/approve_user/', methods=['POST'])
def approve_user():
    dbmain.approveUser(ObjectId(request.form['user']), ObjectId(request.form['fair']))
    return jsonify(result="Success")

@ajax.route('/reject_user/', methods=['POST'])
def reject_user():
    dbmain.removeRegistration(ObjectId(request.form['user']), ObjectId(request.form['fair']))
    return jsonify(result="Success")

@ajax.route('/students_to_pair/', methods=['POST'])
def students_to_pair():
    students = dbmain.studentsToPair(ObjectId(request.form['fair']), request.form['repeats'])
    result = []
    for student in students:
        result.append({"id":str(student['_id']), "first":student['first'], "last":student['last']})
    return jsonify(result)

@ajax.route('/mentors_to_pair/', methods=['POST'])
def mentors_to_pair():
    mentors = dbmain.mentorsToPair(ObjectId(request.form['fair']), request.form['repeats'])
    result = []
    for mentor in mentors:
        result.append({"id":str(mentor['_id']), "first":mentor['first'], "last":mentor['last']})
    return jsonify(result)

@ajax.route('/pair/', methods=['POST'])
def pair():
    if not dbmain.pairingExists(ObjectId(request.form['fair']), ObjectId(request.form['student']), ObjectId(request.form['mentor'])):
        dbmain.addPairing(ObjectId(request.form['fair']), ObjectId(request.form['student']), ObjectId(request.form['mentor']))
        if not dbmain.hasPrimaryPartner(ObjectId(request.form['student'])):
            dbmain.changePrimaryPartner(ObjectId(request.form['student']), ObjectId(request.form['mentor']))
        if not dbmain.hasPrimaryPartner(ObjectId(request.form['mentor'])):
            dbmain.changePrimaryPartner(ObjectId(request.form['mentor']), ObjectId(request.form['student']))
        # create a conversation between the two partners if it does not exist yet
        dbcomm.addConversation([ObjectId(request.form['student']), ObjectId(request.form['mentor'])])
    return jsonify(result="Success")

@ajax.route('/remove_pairing/', methods=['POST'])
def remove_pairing():
    dbmain.deletePairingByID(ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/mentors_needing_trainers/', methods=['POST'])
def mentors_needing_trainers():
    mentors = dbmain.mentorsNeedingTrainers(ObjectId(request.form['fair']), request.form['repeats'])
    result = []
    for mentor in mentors:
        result.append({"id":str(mentor['_id']), "first":mentor['first'], "last":mentor['last']})
    return jsonify(result)

@ajax.route('/fair_administrators/', methods=['POST'])
def fair_administrators():
    administrators = dbmain.administrators(ObjectId(request.form['fair']))
    result = []
    for admin in administrators:
        result.append({"id":str(admin["_id"]), "first":admin["first"], "last":admin["last"]})
    return jsonify(result)

@ajax.route('/pair_trainer/', methods=['POST'])
def pair_trainer():
    if not dbmain.trainingExists(ObjectId(request.form['fair']), ObjectId(request.form['mentor']), ObjectId(request.form['trainer'])):
        dbmain.assignTrainer(ObjectId(request.form['fair']), ObjectId(request.form['mentor']), ObjectId(request.form['trainer']))
    dbcomm.addConversation([ObjectId(request.form['mentor']), ObjectId(request.form['trainer'])])
    return jsonify(result="Success")

@ajax.route('/remove_training/', methods=['POST'])
def remove_training():
    dbmain.deleteTrainingByID(ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/post_announcement/', methods=['POST'])
def post_announcement():
    dbmain.addAnnouncement(ObjectId(request.form['fair']), ObjectId(request.form['author']), time(), request.form['title'], request.form['contents'])
    return jsonify(result="Success")

@ajax.route('/remove_announcement/', methods=['POST'])
def remove_announcement():
    dbmain.deleteAnnouncementByID(ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/update_permissions/', methods=['POST'])
def update_permissions():
    dbmain.setAccessLevel(ObjectId(request.form['user']), ObjectId(request.form['fair']), request.form['level'])
    return jsonify(result="Success")

@ajax.route('/make_primary_partner/', methods=['POST'])
def make_primary_partner():
    dbmain.changePrimaryPartner(ObjectId(session['id']), ObjectId(request.form['id']))
    return jsonify(result="Success")

@ajax.route('/update_project/', methods=['POST'])
def update_project():
    dbproj.editProject(ObjectId(request.form['project_id']), request.form['field'], request.form['value'])
    return jsonify(result="Success")

@ajax.route('/project_field/', methods=['POST'])
def project_field():
    result = dbproj.projectField(ObjectId(request.form['project_id']), request.form['field'])
    return jsonify(result=result)

@ajax.route('/messages_in_conversation/', methods=['POST'])
def messages_in_conversation():
    conversation_id = request.form['conversation_id']
    messages = dbcomm.messagesInConversation(ObjectId(conversation_id))
    members = dbcomm.convoMembers(ObjectId(session['id']), dbcomm.conversationByID(ObjectId(conversation_id)), True)
    return jsonify(messages=messages, members=members)

@ajax.route('/send_message/', methods=['POST'])
def send_message():
    conversation_id = request.form['conversation_id']
    author_id = session['id']
    timestamp = time()
    subject = request.form['subject']
    message = request.form['message']
    dbcomm.addMessage(ObjectId(conversation_id), ObjectId(author_id), timestamp, subject, message)
    # get recipients of message
    members = dbcomm.otherUsersInConversation(ObjectId(author_id), dbcomm.conversationByID(ObjectId(conversation_id)))
    # send message
    t = threading.Thread(target=mailer.send_new_message_mail, args=[members, dbmain.currentUser(), message])
    t.setDaemon(False)
    t.start()
    return jsonify(result="Success")

@ajax.route('/get_conversations/', methods=['POST'])
def get_conversations():
    user_id = ObjectId(session['id'])
    conversations = dbcomm.conversationsForUser(user_id)
    return jsonify(conversations=conversations)

@ajax.route('/get_watched_conversations/', methods=['POST'])
def get_watched_conversations():
    user_id = ObjectId(session['id'])
    conversations = dbcomm.watchedConversationsForUser(user_id)
    return jsonify(conversations=conversations)

@ajax.route('/new_conversation/', methods=['POST'])
def new_conversation():
    members = []
    requested_members = json.loads(request.form['members'])
    if len(requested_members) == 0:
        return jsonify(result=0)
    for member in requested_members:
        members.append(ObjectId(member))
    members.append(ObjectId(session['id']))
    if dbcomm.conversationExists(members):
        return jsonify(result=-1)
    else:
        inserted_id = str(dbcomm.addConversation(members))
        return jsonify(result=1, convo_id=inserted_id)
    
@ajax.route('/submit_for_approval/', methods=['POST'])
def submit_for_approval():
    author_id = ObjectId(request.form['author_id'])
    fair_id = ObjectId(request.form['fair_id'])
    dbproj.changeApprovalStatus(author_id, fair_id, -1)
    return jsonify(result="Success")

@ajax.route('/change_approval_status/', methods=['POST'])
def change_approval_status():
    author_id = ObjectId(request.form['author_id'])
    fair_id = ObjectId(request.form['fair_id'])
    new_status = request.form['new_status']
    dbproj.changeApprovalStatus(author_id, fair_id, new_status)
    return jsonify(result="Success")

@ajax.route('/add_task/', methods=['POST'])
def add_task():
    name = request.form['name']
    value = request.form['value']
    fair_id = ObjectId(request.form['fair_id'])
    task_id = dbtasks.createTask(fair_id, name, value)
    dbtasks.generateProgressesForTask(task_id)
    return jsonify(result="Success")

@ajax.route('/get_tasks/', methods=['POST'])
def get_tasks():
    fair_id = ObjectId(request.form['fair_id'])
    tasks = dbtasks.tasksForFair(fair_id)
    return jsonify(tasks=tasks)

@ajax.route('/edit_task/', methods=['POST'])
def edit_task():
    name = request.form['name']
    value = request.form['value']
    task_id = ObjectId(request.form['task_id'])
    dbtasks.editTask(task_id, name, value)
    return jsonify(result="Success")

@ajax.route('/delete_task/', methods=['POST'])
def delete_task():
    task_id = ObjectId(request.form['task_id'])
    dbtasks.removeTask(task_id)
    return jsonify(result="Success")

@ajax.route('/update_progress/', methods=['POST'])
def update_progress():
    user_id = ObjectId(request.form['user_id'])
    task_id = ObjectId(request.form['task_id'])
    points = request.form['points']
    none = request.form['none'] == "true"
    dbtasks.updateProgress(user_id, task_id, None if none else points)
    return jsonify(result="Success")

@ajax.route('/change_password/', methods=['POST'])
def change_password():
    user = dbmain.currentUser()
    old_pass = request.form['old_pass']

controllers/fair.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from model import helpers, dbmain, dbtasks
from bson import ObjectId
import re

fair = Blueprint('fair', __name__,
                        template_folder='../templates/fair')

@fair.before_request
def check():
    if 'id' not in session:
        return redirect(url_for('home.homepage'))

@fair.route('/')
def fair_page():
    return redirect(url_for('fair.manage'))

# Permissions: everyone can access
@fair.route('/manage/', methods=['GET', 'POST'])
def manage():
    error = None
    if request.method == 'POST' and request.form['type'] == 'Register':
        name = request.form['name']
        date = request.form['date']
        location = request.form['location']
        private = 'private' in request.form
        r = re.compile('\d{1,2}/\d{1,2}/\d{4}')
        if name == "":
            error = "You did not specify a name for the fair."
        elif r.match(date) is None:
            error = "You did not specify a valid date."
        elif location == "":
            error = "You did not specify a valid location."
        else:
            fair_id = dbmain.addFair(name, date, location, private)
            dbmain.addRegistration(ObjectId(session['id']), fair_id, True)
            dbmain.addPermission(ObjectId(session['id']), fair_id, "is_owner")
            dbmain.changePrimaryFair(ObjectId(session['id']), fair_id)
    if request.method == 'POST' and request.form['type'] == 'Join':
        fair = dbmain.fair(request.form['fair'])
        approved = False if fair['private'] else True
        dbmain.addRegistration(ObjectId(session['id']), ObjectId(request.form['fair']), approved)
        dbtasks.generateProgressesForUser(ObjectId(session['id']), ObjectId(request.form['fair']))
        dbmain.changePrimaryFair(ObjectId(session['id']), ObjectId(request.form['fair']))
    if request.method == 'POST' and request.form['type'] == 'Leave':
        dbmain.removeRegistration(ObjectId(session['id']), ObjectId(request.form['fair']))
        dbtasks.deleteProgressesForUserInFair(ObjectId(session['id']), ObjectId(request.form['fair']))
        if ObjectId(request.form['fair']) == dbmain.currentUser()['primary']:
            dbmain.changePrimaryFair(ObjectId(session['id']), None)
    registration = dbmain.fairsForUser(ObjectId(session['id']))
    unjoined = dbmain.unjoinedFairs(ObjectId(session['id']))
    return render_template('manage.html', user=dbmain.currentUser(), registration=registration, unjoined=unjoined, error=error)

# Permissions: only those who Can Approve Users can access (Partial Access or greater)
@fair.route('/requests/')
def requests():
    if not dbmain.isAdmin():
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pfid = dbmain.currentPFID()
    if pfid == None:
        return render_template('errors/no_primary_fair.html', user=dbmain.currentUser())
    if not dbmain.permissionCheck(ObjectId(session['id']), pfid, "can_approve_users"):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    requests = dbmain.pendingRequestsForFair(pfid)
    students = []
    mentors = []
    admins = []
    for request in requests:
        if request['acct_type'] == "Student":
            students.append(request)
        elif request['acct_type'] == "Mentor":
            mentors.append(request)
        elif request['acct_type'] == "Administrator":
            admins.append(request)
    return render_template('requests.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), students=students, mentors=mentors, admins=admins)

# Permissions: only those who Can Pair Users can access (Partial Access or greater)
@fair.route('/pair/')
def pair():
    if not dbmain.isAdmin():
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pfid = dbmain.currentPFID()
    if pfid == None:
        return render_template('errors/no_primary_fair.html', user=dbmain.currentUser())
    if not dbmain.permissionCheck(ObjectId(session['id']), pfid, "can_pair_users"):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pairings = dbmain.pairingsForFair(pfid)
    return render_template('pair.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), pairings=pairings)

# Permissions: only those who can Pair Trainers can access (Full Access or greater)
@fair.route('/trainers/')
def trainers():
    if not dbmain.isAdmin():
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pfid = dbmain.currentPFID()
    if pfid == None:
        return render_template('errors/no_primary_fair.html', user=dbmain.currentUser())
    if not dbmain.permissionCheck(ObjectId(session['id']), pfid, "can_pair_trainers"):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pairings = dbmain.trainersForFair(pfid)
    return render_template('trainers.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), pairings=pairings)

# Permissions: only those who Can Post Announcements can access (Full Access or greater)
@fair.route('/announcements/')
def announcements():
    if not dbmain.isAdmin():
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pfid = dbmain.currentPFID()
    if pfid == None:
        return render_template('errors/no_primary_fair.html', user=dbmain.currentUser())
    if not dbmain.permissionCheck(ObjectId(session['id']), pfid, "can_post_announcements"):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    announcements = dbmain.announcements(dbmain.currentUser(), pfid)
    return render_template('announcements.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), announcements=announcements)

# Permissions: only owners can edit
@fair.route('/permissions/')
def permissions():
    if not dbmain.isAdmin():
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pfid = dbmain.currentPFID()
    if pfid == None:
        return render_template('errors/no_primary_fair.html', user=dbmain.currentUser())
    if not dbmain.hasPermission(ObjectId(session['id']), pfid, "is_owner"):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    administrators = dbmain.administrators(dbmain.currentFair()['_id'])
    adminlist = []
    for administrator in administrators:
        administrator['alevel'] = dbmain.accessLevelForUser(administrator['_id'], dbmain.currentPFID())
        adminlist.append(administrator)
    return render_template('permissions.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), admins=adminlist)

@fair.route('/partner/')
def partner():
    if (not dbmain.isStudent()) and (not dbmain.isMentor()):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pfid = dbmain.currentPFID()
    partners = []
    if dbmain.isStudent():
        partners = dbmain.pairingsForStudent(dbmain.currentUser()['_id'])
    else:
        partners = dbmain.pairingsForMentor(dbmain.currentUser()['_id'])
    primary = dbmain.primaryPartner(dbmain.currentUser()['_id'])
    return render_template('partner.html', user=dbmain.currentUser(), partners=partners, primary=primary)

templates/fair/announcements.html
{% extends "fair/fairbase.html" %}

{% block contents %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Post New Announcement</h4>
        </div>
        <div class="content">
           <div class="row">
               <div class="col-sm-12">
                   <input style="margin-bottom:10px;" class="form-control" type="text" id="announcement-title" placeholder="Announcement Title">
                   <textarea class="form-control" id="announcement-contents" placeholder="Announcement" rows="5"></textarea>
               </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                       <br />
                    <button onclick="postAnnouncement()" class="btn btn-primary">Post Announcement</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Announcements</h4>
        </div>
        <div class="content">
            <table id="announcements-table" class="table table-striped table-bordered" style="font-size:14px;" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Announcement</th>
                        <th>Date</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                   {% for announcement in announcements %}
                    <tr>
                        <td><b>{{ announcement.title }}</b><br />{{ announcement.contents }}</td>
                        <td>{{ announcement.datetime }}</td>
                        <td><button onclick="deleteAnnouncement('{{ announcement['_id'] }}')" class="btn btn-danger btn-xs">Delete</button></td>
                    </tr>
                   {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-announcements").addClass('active');
    $('#announcements-table').DataTable();
});
    
function postAnnouncement() {
    var parameters = {
        fair: "{{ fair['_id']|string }}",
        author: "{{ user['_id']|string }}", 
        title: $('#announcement-title').val(), 
        contents: $('#announcement-contents').val()
    }
    
    $.post("{{ url_for('ajax.post_announcement') }}", parameters, function(data, textStatus) {
        location.reload(true);
    }, "json");
}
    
function deleteAnnouncement(id) {
    var parameters = {
        id: id
    }
    
    $.post("{{ url_for('ajax.remove_announcement') }}", parameters, function(data, textStatus) {
        location.reload(true);
    }, "json");
}

</script>
{% endblock %}

templates/fair/fairbase.html
{% extends "portal/portalbase.html" %}

{% block content %}
<h2>Fair</h2>
<hr>
<div class="row">
    <ul class="nav nav-tabs">
      <li id="navbar-manage"><a href="{{ url_for('fair.manage') }}">Manage</a></li>
      
      {% if user.acct_type == "Administrator" %}
      <li id="navbar-requests"><a href="{{ url_for('fair.requests') }}">Requests</a></li>
      <li id="navbar-pairings"><a href="{{ url_for('fair.pair') }}">Pairings</a></li>
      <li id="navbar-trainers"><a href="{{ url_for('fair.trainers') }}">Trainers</a></li>
      <li id="navbar-announcements"><a href="{{ url_for('fair.announcements') }}">Announcements</a></li>
      <li id="navbar-permissions"><a href="{{ url_for('fair.permissions') }}">Permissions</a></li>
      {% elif user.acct_type == "Mentor" %}
      <li id="navbar-partner"><a href="{{ url_for('fair.partner') }}">Student</a></li>
      {% elif user.acct_type == "Student" %}
      <li id="navbar-partner"><a href="{{ url_for('fair.partner') }}">Mentor</a></li>
      {% endif %}
    </ul>
</div>
<br />
{% block contents %}{% endblock %}
{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-fair').addClass('active');   
});
</script>
{% endblock %}

templates/fair/pair.html
{% extends "fair/fairbase.html" %}

{% block contents %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Pair Students and Mentors</h4>
        </div>
        <div class="content">
           <div class="row">
                <div class="col-sm-6">
                    <select id="student-select" class="form-control">
                        <option value=0 disabled selected>Select a Student</option>
                    </select>
                    <input type="checkbox" id="student-repeats"> Show already paired students
                </div>
                <div class="col-sm-6">
                    <select id="mentor-select" class="form-control">
                        <option value=0 disabled selected>Select a Mentor</option>
                    </select>
                    <input type="checkbox" id="mentor-repeats"> Show already paired mentors
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <br />
                    <button onclick="pair()" class="btn btn-primary">Pair</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Current Pairings</h4>
        </div>
        <div class="content">
            <table id="pairing-table" class="table table-striped table-bordered" style="font-size:14px;" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Student</th>
                        <th>Mentor</th>
                        <th>Delete Pairing</th>
                    </tr>
                </thead>
                <tbody>
                   
                    {% for pairing in pairings %}
                    <tr>
                    <td>{{ pairing['student']['first'] }} {{ pairing['student']['last'] }}</td>
                    <td>{{ pairing['mentor']['first'] }} {{ pairing['mentor']['last'] }}</td>
                    <td><button onclick="removePairing('{{ pairing['_id']|string }}')" class="btn btn-xs btn-danger">Delete Pairing</button></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-pairings").addClass('active');
    $('#student-repeats').prop('checked', false);
    $('#mentor-repeats').prop('checked', false);
    fillStudentPairing();
    fillMentorPairing();
    $('#student-repeats').change(function() {
        fillStudentPairing();
    });
    $('#mentor-repeats').change(function() {
        fillMentorPairing();
    });
    $('#pairing-table').DataTable();
});
    
function fillStudentPairing() {
    var parameters = {
        fair: "{{ fair['_id']|string }}",
        repeats: $('#student-repeats').prop('checked')
    }
        
    $.post("{{ url_for('ajax.students_to_pair') }}", parameters, function(data, textStatus) {
        contents = "<option value=0 disabled selected>Select a Student</option>";
        for (var i = 0; i <data.length; i++) {
            contents += "<option value='" + data[i]['id'] + "'>" + data[i]['first'] + " " + data[i]['last'] + "</option>";
        }
        $('#student-select').html(contents);
    }, "json");
}
    
function fillMentorPairing() {
    var parameters = {
        fair: "{{ fair['_id']|string }}",
        repeats: $('#mentor-repeats').prop('checked')
    }
        
    $.post("{{ url_for('ajax.mentors_to_pair') }}", parameters, function(data, textStatus) {
        contents = "<option value=0 disabled selected>Select a Mentor</option>";
        for (var i = 0; i <data.length; i++) {
            contents += "<option value='" + data[i]['id'] + "'>" + data[i]['first'] + " " + data[i]['last'] + "</option>";
        }
        $('#mentor-select').html(contents);
    }, "json");
}
    
function pair() {
    var parameters = {
        fair: "{{ fair['_id']|string }}",
        student: $('#student-select').val(),
        mentor: $('#mentor-select').val()
    }
    
    $.post("{{ url_for('ajax.pair') }}", parameters, function(data, textStatus) {
        location.reload(true);
    }, "json");
}

function removePairing(id) {
    var parameters = {
        fair: "{{ fair['_id']|string }}",
        id: id
    }
    
    $.post("{{ url_for('ajax.remove_pairing') }}", parameters, function(data, textStatus) {
        location.reload(true);
    }, "json");
}
    
</script>
{% endblock %}

templates/fair/partner.html
{% extends "fair/fairbase.html" %}

{% block contents %}

{% if error is defined and error != None %}
<div class="alert alert-danger"> <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> <strong>Error:</strong> {{ error }} </div>
{% endif %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Partner List</h4>
        </div>
        <div class="content table-responsive table-full-width">
            <table class="table table-hover table-striped" style="font-size:14px;">
                <thead>
                    <th>Name</th>
                    <th>School</th>
                    <th>Email</th>
                    <th>Primary</th>
                </thead>
                <tbody>
                    {% for partner in partners %}
                    
                    <tr>
                        <td>{{ partner.first }} {{ partner.last }}</td>
                        <td>{{ partner.school }}</td>
                        <td><a href="mailto:{{ partner.email }}">{{ partner.email }}</a></td>
                        <td>{% if partner['_id'] == primary %}Primary{% else %}<button onclick="makePrimary('{{ partner['_id']|string }}'); return false;" class="btn btn-xs btn-default">Make Primary</button>{% endif %}</td>
                    </tr>
                    {% endfor %}
                    {% if partners|length == 0 %}
                    <tr>
                        <td colspan="4">You are not currently assigned to any partner.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-partner").addClass('active'); 

});

    
function makePrimary(id) {
    var parameters = {
        id: id
    }
    
    $.post("{{ url_for('ajax.make_primary_partner') }}", parameters, function(data, textStatus) {
        window.location.href = window.location.href;
    }, "json");
}

</script>
{% endblock %}

templates/fair/trainers.html
{% extends "fair/fairbase.html" %}


{% block contents %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Current Mentor Trainers</h4>
        </div>
        <div class="content">
            <table id="pairing-table" class="table table-striped table-bordered" style="font-size:14px;" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Mentor</th>
                        <th>Trainer</th>
                    </tr>
                </thead>
                <tbody>
                   
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-trainers").addClass('active');
    $('#pairing-table').DataTable();
});
   
</script>
{% endblock %}