controllers/participants.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from model import helpers, dbmain, dbproj, dbtasks, dbcomm
from bson import ObjectId
import re

# "Participants" is the name for the "Rosters" tab, was renamed on the interface earlier
participants = Blueprint('participants', __name__,
                        template_folder='../templates/participants')

@participants.before_request
def check():
    if 'id' not in session:
        return redirect(url_for('home.homepage'))
    if not dbmain.isAdmin():
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    pfid = dbmain.currentPFID()
    if pfid == None:
        return render_template('errors/no_primary_fair.html', user=dbmain.currentUser())

@participants.route('/')
def roster():
    pfid = dbmain.currentPFID()
    roster = dbproj.roster(pfid)
    students = roster['students']
    mentors = roster['mentors']
    
    # if not full access, then filter approvals to only show allowed approvals
    if not dbmain.permissionCheck(ObjectId(session['id']), pfid, "full_access"):
        new_roster = {"students":[], "mentors":[]}
        for student in students:
            if not dbmain.someTrainingExists(pfid, student['_id'], ObjectId(session['id'])):
                student["access_permitted"] = False
            new_roster["students"].append(student)
        for mentor in mentors:
            if not dbmain.someTrainingExists(pfid, mentor['_id'], ObjectId(session['id'])):
                mentor["access_permitted"] = False
            new_roster["mentors"].append(mentor)
        students = new_roster["students"]
        mentors = new_roster["mentors"]
    
    return render_template('roster.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), students=students, mentors=mentors)

# Permissions: Full Access or greater, or Partial Access with a relationship
@participants.route('/approvals/')
def approvals():
    pfid = dbmain.currentPFID()
    # if no access, then reject
    if not dbmain.permissionCheck(ObjectId(session['id']), pfid, "some_access"):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    
    roster = dbproj.rosterForApprovals(dbmain.currentPFID())
    
    # if not full access, then filter approvals to only show allowed approvals
    if not dbmain.permissionCheck(ObjectId(session['id']), pfid, "full_access"):
        new_roster = {"-2":[], "-1":[], "0":[], "1":[]}
        for group in roster:
            for student in roster[group]:
                if dbmain.someTrainingExists(pfid, student['_id'], ObjectId(session['id'])):
                    new_roster[str(int(student["proj_approved"]))].append(student)
        roster = new_roster
        
    rejected = roster["-2"]
    pending = roster["-1"]
    notsubmitted = roster["0"]
    approved = roster["1"]
    return render_template('approvals.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), rejected=rejected, pending=pending, notsubmitted=notsubmitted, approved=approved)

# Permissions: Full Access or greater, or Partial Access with a relationship
@participants.route('/<string:username>/')
def profile(username):
    # check to make sure username exists
    user = dbmain.userIfExists(username)
    pfid = dbmain.currentPFID()
    if user == None:
        return render_template('errors/generic_error.html', user=dbmain.currentUser(), title="No User Exists", contents="There is no user with the username that you requested.")
    # check to make sure that the user is registered for the fair
    registered = dbmain.userIsRegisteredForFair(user['_id'], pfid)
    if not registered:
        return render_template('errors/generic_error.html', user=dbmain.currentUser(), title="User Not Registered", contents="The user you requested to view is not registered for this fair.")
    
    # check permissions
    if dbmain.accessLevelForUser(ObjectId(session['id']), pfid) == "No Access":
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    if dbmain.permissionCheck(ObjectId(session['id']), pfid, "some_access") and not dbmain.someTrainingExists(pfid, user['_id'], ObjectId(session['id'])):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    
    # check to see if mentor or student
    utype = user["acct_type"]
    if utype == "Administrator":
        return render_template('errors/generic_error.html', user=dbmain.currentUser(), title="No Profile for Administrators", contents="Users who are administrators do not have profile pages.")
    # get information about the project
    partners = []
    project = None
    progress = None
    if utype == "Mentor":
        pairlist = dbmain.pairingsForMentor(user["_id"])
        for student in pairlist:
            student["project_contents"] = dbproj.projectForUser(student["_id"])
            student["approval_status"] = dbproj.approvalStatusString(dbproj.approvalStatus(student["_id"], pfid))
            student["conversation"] = dbcomm.getConversation([user['_id'], student['_id']])
            student["conversation"] = student["conversation"]["_id"] if student["conversation"] != None else None
            partners.append(student)
        progress = dbtasks.userProgressReport(user['_id'], pfid)
    elif utype == "Student":
        pairlist = dbmain.pairingsForStudent(user["_id"])
        for mentor in pairlist:
            mentor["conversation"] = dbcomm.getConversation([user['_id'], mentor['_id']])
            mentor["conversation"] = mentor["conversation"]["_id"] if mentor["conversation"] != None else None
            partners.append(mentor)
        project = dbproj.projectForUser(user["_id"])
        project["approval_status"] = dbproj.approvalStatusString(dbproj.approvalStatus(user["_id"], pfid))
    # render the profile
    return render_template('profile.html', user=dbmain.currentUser(), subject=user, partners=partners, project=project, progress=progress)

# Permissions: Full Access or greater, or Partial Access with a relationship
@participants.route('/<string:username>/project/')
def project(username):
    # check to make sure username exists
    user = dbmain.userIfExists(username)
    pfid = dbmain.currentPFID()
    if user == None:
        return render_template('errors/generic_error.html', user=dbmain.currentUser(), title="No User Exists", contents="There is no user with the username that you requested.")
    # check to make sure that the user is registered for the fair
    registered = dbmain.userIsRegisteredForFair(user['_id'], pfid)
    if not registered:
        return render_template('errors/generic_error.html', user=dbmain.currentUser(), title="User Not Registered", contents="The user you requested to view is not registered for this fair.")
    
    # check permissions
    if dbmain.accessLevelForUser(ObjectId(session['id']), pfid) == "No Access":
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    if dbmain.permissionCheck(ObjectId(session['id']), pfid, "some_access") and not dbmain.someTrainingExists(pfid, user['_id'], ObjectId(session['id'])):
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    
    # check to see if student
    utype = user["acct_type"]
    if utype != "Student":
        return render_template('errors/generic_error.html', user=dbmain.currentUser(), title="No Projects for Non-Students", contents="Only students have projects.")
    # get the user's project
    project = dbproj.projectForUser(user["_id"])
    # fields to show. Each is array of form [Human-Readable Name, Database Field, Rows for Editing]
    fields = []
    fields.append(["Title", "title", 1])
    fields.append(["Question", "question", 2])
    fields.append(["Purpose", "purpose", 2])
    fields.append(["Research Rationale", "rationale", 3])
    fields.append(["Hypothesis", "hypothesis", 3])
    fields.append(["Null Hypothesis", "nullhypo", 3])
    fields.append(["Independent Variable", "ivar", 1])
    fields.append(["Dependent Variable", "dvar", 1])
    fields.append(["Controlled Variables", "cvars", 3])
    fields.append(["Control", "control", 2])
    fields.append(["Background Research", "background", 7])
    fields.append(["Materials", "materials", 7])
    fields.append(["Procedure", "procedure", 7])
    fields.append(["Data", "data", 7])
    fields.append(["Discussion of Results", "discussion", 7])
    fields.append(["Conclusion", "materials", 5])
    fields.append(["Acknowledgements", "acknowledgements", 3])
    
    # get project approval information
    approval_status = dbproj.approvalStatus(user['_id'], pfid)
    return render_template('view_project.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), fields=fields, project=project, author=user, approval_status=int(approval_status))

# Anyone can see tasks, only Full Access can edit
@participants.route('/tasks/')
def tasks():
    pfid = dbmain.currentPFID()
    can_edit = dbmain.permissionCheck(ObjectId(session['id']), pfid, "full_access")
    return render_template('tasks.html', user=dbmain.currentUser(), fair=dbmain.currentFair(), can_edit=can_edit)

# Permissions: anyone can see
@participants.route('/progress/')
def progress():
    fair = dbmain.currentFair()
    pfid = dbmain.currentPFID()
    progresses = dbtasks.progressReport(fair["_id"])
    
    # if not full access, then filter approvals to only show allowed approvals
    if not dbmain.permissionCheck(ObjectId(session['id']), pfid, "full_access"):
        new_roster = []
        for mentor in progresses:
            if not dbmain.someTrainingExists(pfid, mentor['_id'], ObjectId(session['id'])):
                mentor["access_permitted"] = False
            new_roster.append(mentor)
        progresses = new_roster
        
    return render_template('progress.html', user=dbmain.currentUser(), fair=fair, progresses=progresses)

controllers/progress.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from model import helpers, dbmain, dbproj, dbtasks
from bson import ObjectId
import re

progress = Blueprint('progress', __name__,
                        template_folder='../templates/progress')

@progress.before_request
def check():
    if 'id' not in session:
        return redirect(url_for('home.homepage'))
    if not dbmain.isMentor():
        return render_template('errors/no_permissions.html', user=dbmain.currentUser())
    if dbmain.currentPFID() == None:
        return render_template('errors/no_primary_fair.html', user=dbmain.currentUser())
    
@progress.route('/')
def mentor_progress():
    fair = dbmain.currentFair()
    progresses = dbtasks.getProgressesForUser(ObjectId(session['id']), fair["_id"])
    return render_template('mentor_progress.html', user=dbmain.currentUser(), fair=fair, progresses=progresses)

templates/participants/approvals.html
{% extends "participants/participantbase.html" %}

{% block contents %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Projects Pending Approval ({{ pending|length }})</h4>
        </div>
        <div class="content">
            <table id="pending-table" class="table table-hover table-striped" style="font-size:14px;">
                <thead>
                    <th>Action</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Project</th>
                    <th>Mentor</th>
                </thead>
                <tbody>
                    {% for student in pending %}
                    <tr>
                        <td id="student-{{ student['_id']|string }}">
                            <button onclick=approve("{{ student['_id']|string }}") class="btn btn-xs btn-primary">Approve</button> 
                            <button onclick=reject("{{ student['_id']|string }}") class="btn btn-xs btn-danger">Reject</button>
                        </td>
                        <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.first }}</a></td>
                        <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.last }}</a></td>
                        <td><a href="{{ url_for('participants.project', username=student.username) }}">{{ student.title }}</a></td>
                        <td>{{ student.partner_list }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Unsubmitted Projects ({{ rejected|length + notsubmitted|length }})</h4>
        </div>
        <div class="content">
            <table id="unsubmitted-table" class="table table-hover table-striped" style="font-size:14px;">
                <thead>
                    <th>Status</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Project</th>
                    <th>Mentor</th>
                </thead>
                <tbody>
                    {% for student in rejected %}
                    <tr>
                        <td id="student-{{ student['_id']|string }}">Rejected</td>
                        <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.first }}</a></td>
                        <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.last }}</a></td>
                        <td><a href="{{ url_for('participants.project', username=student.username) }}">{{ student.title }}</a></td>
                        <td>{{ student.partner_list }}</td>
                    </tr>
                    {% endfor %}
                    {% for student in notsubmitted %}
                    <tr>
                        <td id="student-{{ student['_id']|string }}">Never Submitted</td>
                        <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.first }}</a></td>
                        <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.last }}</a></td>
                        <td><a href="{{ url_for('participants.project', username=student.username) }}">{{ student.title }}</a></td>
                        <td>{{ student.partner_list }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Approved Projects ({{ approved|length }})</h4>
        </div>
        <div class="content">
            <table id="approved-table" class="table table-hover table-striped" style="font-size:14px;">
                <thead>
                    <th>Action</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Project</th>
                    <th>Mentor</th>
                </thead>
                <tbody>
                    {% for student in approved %}
                    <tr>
                        <td id="student-{{ student['_id']|string }}">
                            <button onclick=reject("{{ student['_id']|string }}") class="btn btn-xs btn-danger">Reject</button>
                        </td>
                        <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.first }}</a></td>
                        <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.last }}</a></td>
                        <td><a href="{{ url_for('participants.project', username=student.username) }}">{{ student.title }}</a></td>
                        <td>{{ student.partner_list }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-approvals").addClass('active');
    $('#pending-table').DataTable();
    $('#approved-table').DataTable();
    $('#unsubmitted-table').DataTable();
});
    
function approve(student_id) {
    var parameters = {
        author_id: student_id,
        fair_id: "{{ fair['_id']|string }}",
        new_status: 1
    }
    
    $.post("{{ url_for('ajax.change_approval_status') }}", parameters, function(data, textStatus) {
        $('#student-' + student_id).html('Approved');
    });
}
    
function reject(student_id) {
    var parameters = {
        author_id: student_id,
        fair_id: "{{ fair['_id']|string }}",
        new_status: -2
    }
    
    $.post("{{ url_for('ajax.change_approval_status') }}", parameters, function(data, textStatus) {
        $('#student-' + student_id).html('Rejected');
    });
}

    
</script>
{% endblock %}

templates/participants/participantbase.html
{% extends "portal/portalbase.html" %}

{% block content %}
<h2>Roster</h2>
<hr>
<div class="row">
    <ul class="nav nav-tabs">
      <li id="navbar-roster"><a href="{{ url_for('participants.roster') }}">Roster</a></li>
      <li id="navbar-approvals"><a href="{{ url_for('participants.approvals') }}">Approvals</a></li>
      <li id="navbar-tasks"><a href="{{ url_for('participants.tasks') }}">Tasks</a></li>
      <li id="navbar-progress"><a href="{{ url_for('participants.progress') }}">Progress Report</a></li>
    </ul>
</div>
<br />
{% block contents %}{% endblock %}
{% endblock %}


{% block script %}
<script>
$(document).ready(function() {
    $('#sidebar-participants').addClass('active');   
});
</script>
{% endblock %}

templates/participants/profile.html
{% extends "participants/participantbase.html" %}

{% block contents %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">User Profile: {{ subject.first }} {{ subject.last }}</h4>
        </div>
        <div class="content">
            <i class="fa fa-user fa-fw"></i> {{ subject.acct_type }}<br />
            <i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:{{ subject.email }}">{{ subject.email }}</a><br />
            <i class="fa fa-graduation-cap fa-fw"></i> {{ subject.school }}
        </div>
    </div>
</div>

{% if subject.acct_type == "Student" %}
<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Mentor</h4>
        </div>
        <div class="content">
            <table id="partner-table" class="table table-hover table-striped" style="font-size:14px;">
                <thead>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>School</th>
                    <th>Conversations</th>
                </thead>
                <tbody>
                    {% for partner in partners %}
                    <tr>
                        <td><a href="{{ url_for('participants.profile', username=partner.username) }}">{{ partner.first }}</a></td>
                        <td><a href="{{ url_for('participants.profile', username=partner.username) }}">{{ partner.last }}</a></td>
                        <td>{{ partner.school }}</td>
                        <td><a href="{{ url_for('participants.view_conversation', conversation_id=partner['conversation']|string ) }}">View</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Project</h4>
            <h6 class="title"><a href="{{ url_for('participants.project', username=subject.username) }}">View Project</a></h6>
        </div>
        <div class="content">
            <b>Approval Status:</b> {{ project.approval_status }}<br />
            <b>Title:</b> {{ project.title }}<br />
            <b>Question:</b> {{ project.question }}<br />
        </div>
    </div>
</div>
{% elif subject.acct_type == "Mentor" %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Progress Report</h4>
            <h6 class="title">
                <a href="{{ url_for('participants.user_progress', username=subject.username) }}">View Progress Report</a>
            </h6>
        </div>
        <div class="content">
           <table style="font-size:14px;" class="table table-striped table-hover">
               <thead>
                   <th>Percent</th>
                   <th>Points</th>
                   <th>Points Possible</th>
               </thead>
               <tbody>
                   <tr>
                       <td>{{ '%0.2f' | format(progress['percent']|float) }}%</td>
                       <td>{{ progress['points'] }}</td>
                       <td>{{ progress['total'] }}</td>
                   </tr>
               </tbody>
           </table>
        </div>
    </div>
</div>

{% for partner in partners %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Student: {{ partner.first }} {{ partner.last }}</h4>
            <h6 class="title">
                <a href="{{ url_for('participants.profile', username=partner.username) }}">View Profile</a> / 
                <a href="{{ url_for('participants.project', username=partner.username) }}">View Project</a> / 
                <a href="{{ url_for('participants.view_conversation', conversation_id=partner['conversation']|string ) }}">View Messages</a>
            </h6>
        </div>
        <div class="content">
           <b>Approval Status:</b> {{ partner.approval_status }}<br />
            <b>Project Title:</b> {{ partner.project_contents.title }}<br />
            <b>Question: </b> {{ partner.project_contents.question }}<br />
        </div>
    </div>
</div>


{% endfor %}
{% endif %}

{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-roster").addClass('active');
    

});
    
</script>
{% endblock %}

templates/participants/roster.html
{% extends "participants/participantbase.html" %}

{% block contents %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Students</h4>
        </div>
        <div class="content">
            <table id="student-table" class="table table-hover table-striped" style="font-size:14px;">
                <thead>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>School</th>
                    <th>Mentor</th>
                </thead>
                <tbody>
                    {% for student in students %}
                    
                    <tr>
                        {% if student["access_permitted"] %}
                            <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.first }}</a></td>
                            <td><a href="{{ url_for('participants.profile', username=student.username) }}">{{ student.last }}</a></td>
                        {% else %}
                            <td>{{ student.first }}</td>
                            <td>{{ student.last }}</td>
                        {% endif %}
                        <td>{{ student.school }}</td>
                        <td>{{ student.partner_list }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Mentors</h4>
        </div>
        <div class="content">
            <table id="mentor-table" class="table table-hover table-striped" style="font-size:14px;">
                <thead>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>School</th>
                    <th>Student</th>
                </thead>
                <tbody>
                    {% for mentor in mentors %}
                    
                    <tr>
                       {% if mentor["access_permitted"] %}
                        <td><a href="{{ url_for('participants.profile', username=mentor.username) }}">{{ mentor.first }}</a></td>
                        <td><a href="{{ url_for('participants.profile', username=mentor.username) }}">{{ mentor.last }}</a></td>
                        {% else %}
                        <td>{{ mentor.first }}</td>
                        <td>{{ mentor.last }}</td>
                        {% endif %}
                        <td>{{ mentor.school }}</td>
                        <td>{{ mentor.partner_list }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-roster").addClass('active');
    $('#student-table').DataTable();
    $('#mentor-table').DataTable();
});
    
</script>
{% endblock %}

templates/participants/tasks.html
{% extends "participants/participantbase.html" %}

{% block contents %}

<div class="row">
    <div class="card">
        <div class="header">
            <h4 class="title">Tasks
            {% if can_edit %}<button onclick="showAddTask()" class="btn btn-xs btn-primary" style="float:right;">Add</button>{% endif %}
            </h4>
        </div>
        <div class="content">
            <table id="tasks-table" class="table table-hover table-striped" style="font-size:14px;">
                <thead>
                    <th>Task Name</th>
                    <th>Point Value</th>
                    {% if can_edit %}<th>Edit</th>{% endif %}
                </thead>
                <tbody id="tasks-table-body">
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

{% block outerbody %}
<div id="add-task-modal" class="modal fade" role="dialog" tabindex="-1">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add a Task</h4>
      </div>
      <div class="modal-body">
        <input id="add-task-name" type="text" class="form-control" placeholder="Task Name">
        <br />
        <input id="add-task-value" type="number" class="form-control" placeholder="Point Value">
      </div>
      <div class="modal-footer">
        <span id="add-result-span"></span>
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
        <button onclick="createTask()" type="button" class="btn btn-primary btn-sm">Create Task</button>
      </div>
    </div>

  </div>
</div>

<div id="edit-task-modal" class="modal fade" role="dialog" tabindex="-1">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Task</h4>
      </div>
      <div class="modal-body">
        <input id="edit-task-name" type="text" class="form-control" placeholder="Task Name">
        <br />
        <input id="edit-task-value" type="number" class="form-control" placeholder="Point Value">
      </div>
      <div class="modal-footer">
        <span id="add-result-span"></span>
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
        <span id="delete-button-span"></span>
        <span id="edit-task-button-span"></span>
      </div>
    </div>

  </div>
</div>
{% endblock %}


{% block script %}
{{ super() }}
<script>
$(document).ready(function() {
    $("#navbar-tasks").addClass('active');
    getTasks();
});

{% if can_edit %}
function showAddTask() {
    $('#add-task-modal').modal();
    $('#add-task-name').val('');
    $('#add-task-value').val('');
    setTimeout(function () {
        $('#add-task-name').focus();
    }, 0);
}

function createTask() {
    var parameters = {
        name: $('#add-task-name').val(),
        value: $('#add-task-value').val(),
        fair_id: "{{ fair['_id']|string }}"
    }
    
    $.post("{{ url_for('ajax.add_task') }}", parameters, function(data, textStatus) {
        getTasks();
        $('#add-task-modal').modal('hide');
    });
}
{% endif %}

function getTasks() {
    var parameters = {
        fair_id: "{{ fair['_id']|string }}"
    }
    
    $.post("{{ url_for('ajax.get_tasks') }}", parameters, function(data, textStatus) {
       tasks = data["tasks"];
        table_contents = "";
        for (var i = 0; i < tasks.length; i++) {
            table_contents += '<tr><td>';
            table_contents += '<a id="task-name-' + tasks[i]["_id"] + '" onclick=goToTask("' + tasks[i]["_id"] + '")>';
            table_contents += tasks[i]["name"];
            table_contents += '</a>';
            table_contents += '</td>';
            table_contents += '<td id="task-value-' + tasks[i]["_id"] + '">' + tasks[i]["value"] + '</td>';
            
            {% if can_edit %}
            table_contents += '<td><button onclick=showEditTask("' + tasks[i]["_id"] + '") class="btn btn-default btn-sm">Edit</button><td>';
            {% endif %}
             
            table_contents += '</tr>';
        }
        $('#tasks-table-body').html(table_contents);
    });
}
    
function goToTask(task_id) {
    location.href = "{{ url_for('participants.tasks') }}" + task_id;
}

{% if can_edit %}
function showEditTask(task_id) {
    $('#edit-task-name').val($('#task-name-' + task_id).html());
    $('#edit-task-value').val($('#task-value-' + task_id).html());
    $('#delete-button-span').html('<button onclick=deleteTask("' + task_id + '") type="button" class="btn btn-danger btn-sm">Delete Task</button>');
    $('#edit-task-button-span').html('<button onclick=editTask("' + task_id + '") type="button" class="btn btn-primary btn-sm">Edit Task</button>');
    $('#edit-task-modal').modal();
}
    
function editTask(task_id) {
    var parameters = {
        name: $('#edit-task-name').val(),
        value: $('#edit-task-value').val(),
        task_id: task_id
    }
    
    $.post("{{ url_for('ajax.edit_task') }}", parameters, function(data, textStatus) {
        getTasks();
        $('#edit-task-modal').modal('hide');
    }, "json");
}
    
function deleteTask(task_id) {
     var parameters = {
         task_id : task_id
     }
     
     $.post("{{ url_for('ajax.delete_task') }}", parameters, function(data, textStatus) {
         getTasks();
         $('#edit-task-modal').modal('hide');
     }, "json");
}
{% endif %}
    
</script>
{% endblock %}